### ISSUE TITLE
 Error running the code: SVD did not converge

### ISSUE THREAD

**Issue by kareth-leon** [liuyang12/DeSCI#1]
### I downloaded and ran the code in the CASSI mode. After some time, it appears this error:
```
Error using wnnm (line 11)
SVD did not converge.
```
Do you know what can I do for fixing it?
Thank you!

**Comment by liuyang12** [comment]
Hi @mrkcel ,

Thanks for your comment.

For the `svd()` problem, I would like to know the version of MATLAB in use and its subversion (Update x). We have tested the code in MATLAB R2017b and R2018b. We also get the `svd()` errors when we run this code on R2018a (without updates), which has known bugs for `svd()` function (see https://www.mathworks.com/support/bugreports/details/1768487 for details). It is supposed to be resolved in updated subversions and later major versions.

Best,
Yang

**Comment by kareth-leon** [comment]
Thanks for answering @liuyang12 !
You are right, the problem is solved by updating the Matlab version. I was running the code in the R2018a version. I tested the code in Matlab R2018b, and it ran well. Thanks.
