### ISSUE TITLE
Hello author, can you provide the video of the test in your paper? The name is traffic drop runner

### ISSUE THREAD

**Issue by nuist-xinyu** [liuyang12/DeSCI#2]

**Comment by liuyang12** [comment]
Sure! Here it goes.

Google Drive link: https://drive.google.com/drive/folders/1atuHn8lH_dGigH5wu0OIMsroMfK08wgn?usp=sharing
Baidu Drive link: https://pan.baidu.com/s/1Ob5eAsjVbQ6cQ1xXZiJPuA
